menu:
  Home: /
  Archives: /archives
  GitHub: https://github.com/howiefh
  RSS: /atom.xml

widgets: 
- search
- about_me
- category
- tagcloud
- calendar
- recent_posts
- links
- duoshuo_recent_comments

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable: false
  pubid:
  facebook: true
  twitter: true
  google: true
  pinterest: true

fancybox: true

google_analytics: UA-40492061-1
rss: /atom.xml

links:
- name: 404 page
  link: http://yibo.iyiyun.com/js/yibo404/key/1

duoshuo: howiefh

about_me:
  title: ABOUT ME
  avatar: /images/okal-eltocat.jpeg
  texts:
  - Do one thing and do it well!
  - <a href="http://hi.baidu.com/idea_star" target="_BLANK">百度空间</a>
